### ISSUE TITLE
Error when using 'valid' padding

### ISSUE THREAD

**Issue by Andrea-Oliveri** [deephealthproject/pyeddl#21]
Good Morning,
I have an issue running a basic CNN: execution fails on the Conv and Maxpool lines when trying to build the network with this message:
```
Traceback (most recent call last):
  File "model_basic_lopo.py", line 87, in <module>
    model = getModel()
  File "/home/andrea/Desktop/folder_andrea/src/utils.py", line 65, in getModel
    layer = Conv(layer, 16, [3, 5], strides=[1,2], padding='valid')
RuntimeError: Incorrect padding type (ConvolDescriptor::ConvolDescriptor)
```
which suggests that the padding 'valid' is not yet implemented in the library. However, from the eddl documentation, this is not the case as here: [https://deephealthproject.github.io/eddl/layers/convolutional.html?highlight=conv#_CPPv4N4eddl4ConvE5layeriRK6vectorIiERK6vectorIiE6stringbiRK6vectorIiE6string](url) it sais it is to date possible to choose between 'none', 'same' and 'valid'. Can you please confirm me this fonctionality is not yet implemented and, if so, when it will be?
Thank you in advance for your help.

**Comment by RParedesPalacios** [comment]
Sorry for the confusion, in fact in some place says:

@param padding  One of "none", "valid" or "same"

however "valid" is the same that "none"

**Comment by Andrea-Oliveri** [comment]
Thank you.
