### ISSUE TITLE
GaussianNoise seems related to memory free issues

### ISSUE THREAD

**Issue by simleo** [deephealthproject/pyeddl#4]
In the current version of the [eddl_dae_class](https://github.com/deephealthproject/pyeddl/blob/87735d6651cbe2d2b4b0274177a1d7e7ab492480/examples/NN/eddl_dae_class.py) example, the `# layer = eddl.GaussianNoise(layer, 0.5)` line is commented out. If the comment is removed, the program runs, but as the interpreter exits, a `malloc_consolidate(): invalid chunk size` error appears.

Adding that line to `eddl_mlp.py` or `eddl_ae.py` leads to the same problem.

**Comment by RParedesPalacios** [comment]
Simone, so it seems that should be something related to the layer destroy? 
We will take a look...

**Comment by simleo** [comment]
It turns out that all it takes to get the error is the following three lines:

```python
import pyeddl._core.eddl as eddl

in_ = eddl.Input([784])
gn = eddl.GaussianNoise(in_, 0.5)
```

Output:
```
malloc_consolidate(): invalid chunk size
Aborted (core dumped)
```

**Comment by RParedesPalacios** [comment]
Solved
