### ISSUE TITLE
Selu output problem

### ISSUE THREAD

**Issue by georgemavrakis-wings** [deephealthproject/pyeddl#56]
Good afternoon,

I have a problem with the Selu layer. More specifically, it seems that it does not calculate its output correctly. I have tested other layers instead (e.g. Elu, ReLu) and the output is as expected. All layers have been compared with PyTorch and seem to produce the same output, except for Selu.

I provide the input of the Selu layer (ndarray), as well as the output of the Selu layer and the pytorch Selu layer in the zip file.

[selu_input_outputs.zip](https://github.com/deephealthproject/pyeddl/files/6084754/selu_input_outputs.zip)

Thank you in advance.

**Comment by simleo** [comment]
Hi. PyEDDL provides Python bindings for the C++ [EDDL](https://github.com/deephealthproject/eddl) API. Behavior should only be different if the bindings are passing wrong default parameters to the C++ function, but `Selu` has no parameters, so this should be addressed in EDDL. Please open an issue in the EDDL repo -- you can link to this one so you don't have to redo it from scratch. Make sure you specify the EDDL version -- there's a table that maps PyEDDL version to EDDL version [here](https://deephealthproject.github.io/pyeddl/installation.html#install-pyeddl).

**Comment by simleo** [comment]
Solved upstream (https://github.com/deephealthproject/eddl/issues/269).
