### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by jonandergomez** [deephealthproject/pyeddl#62]
Unsuccessful installation by means of the command:

      conda install -c dhealth -c bioconda -c conda-forge pyeddl-cudnn

Same result after installing a new (recent) version of Anaconda3 and updating it before trying the installation. In all cases the versions proposed by "conda install" are older versions that do not include the version 1.0.* of EDDL.

When trying with 'pip' it seems that version 1.0.0 of pyedd-cudnn is found, but a problem with pybind11 arises. I tried to manually install the pybind11, then 'pip' requires another version, not the 2.6.2, and tries to remove it, then installation aborts.

I tried this in two different machines, both with Linux, and same result. In both cases with a recent installation of Anaconda3.

Thanks in advance,

Jon

**Comment by simleo** [comment]
Conda packages haven't been updated to 1.0* yet, I'm still working on it. I will post an update when they are available.

As for pybind11, pyeddl requires a version less than 2.6:

```
pip install 'pybind11<2.6'
```

**Comment by jonandergomez** [comment]
Thanks a lot Simone. Version 0.14 installed with no problems. Version 1.0.0 after installing pybind11 as you commented, raises another error when setup.py is automatically executed. Here the output:
 ERROR: Command errored out with exit status 1:
   command: /home/jojaca/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cfjm4fbe/pyeddl_d7755a6d3adf4dca8bd1fa86391b8c41/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cfjm4fbe/pyeddl_d7755a6d3adf4dca8bd1fa86391b8c41/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ljstph_n
       cwd: /tmp/pip-install-cfjm4fbe/pyeddl_d7755a6d3adf4dca8bd1fa86391b8c41/
  Complete output (22 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/pyeddl
  copying pyeddl/utils.py -> build/lib.linux-x86_64-3.8/pyeddl
  copying pyeddl/tensor.py -> build/lib.linux-x86_64-3.8/pyeddl
  copying pyeddl/eddl.py -> build/lib.linux-x86_64-3.8/pyeddl
  copying pyeddl/version.py -> build/lib.linux-x86_64-3.8/pyeddl
  copying pyeddl/__init__.py -> build/lib.linux-x86_64-3.8/pyeddl
  running build_ext
  building 'pyeddl._core' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  gcc -pthread -B /home/jojaca/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/home/jojaca/anaconda3/lib/python3.8/site-packages/pybind11/include -I/home/jojaca/anaconda3/lib/python3.8/site-packages/pybind11/include -I/home/jojaca/anaconda3/include/python3.8 -c src/_core.cpp -o build/temp.linux-x86_64-3.8/src/_core.o -std=c++11 -fvisibility=hidden -DEDDL_WITH_PROTOBUF
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/_core.cpp:2:10: fatal error: eddl/descriptors/tensor_descriptors.h: No such file or directory
      2 | #include <eddl/descriptors/tensor_descriptors.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyeddl


I tried to install the eddl-cudnn version 1.0.2.a before, but the problem persists.

Regards,

Jon

**Comment by simleo** [comment]
It looks like it's not finding the EDDL includes. This kind of problem can be fixed by adding the relevant directory to the include path. For instance:

```
export CPATH="/my/extra/include/dir:${CPATH}"
```

Anyway, don't try that just yet :slightly_smiling_face:. I have now updated all conda packages to EDDL 1.0.2a / PyEDDL 1.0.0. Start from a clean slate and retry `conda install -c conda-forge -c dhealth pyeddl-cudnn`: you should pick up version 1.0.0.

For reference, here is the [Dockerfile with the full sequence I've tested successfully](https://github.com/deephealthproject/conda_builds/blob/a482b9418ff9dcaf4b6dd86db6c72e2e30938cb2/cudnn/Dockerfile.pyeddl-test-cloud).

**Comment by jonandergomez** [comment]
Thanks a lot Simone,

Now it is perfect with conda command.

Best regards,

Jon
