### ISSUE TITLE
Pyeddl with CUDA performance degradation

### ISSUE THREAD

**Issue by RParedesPalacios** [deephealthproject/pyeddl#67]
I have run some experiments with CIFAR to compare C++ and Python APIs. Surprisingly the CUDA version on Python is extremely slow comparing to the C++ counterpart.

Batch Time : 

EDDL (C++)
- cudnn: 0.0439s
- cuda:  0.0546s

PYEDDL:
- cudnn: 0.0433s
- cuda: 0.5850s **<----- 10x slower**

**Comment by simleo** [comment]
Hi Roberto. We need some more information if we want to try and reproduce this. Which versions of EDDL / PyEDDL are you using? Did you install from source or Conda, or are you using the Docker image? What programs are you running (C++ and Python), and with which settings?

**Comment by simleo** [comment]
The reason why I set the default to "low_mem" in the examples is that some of them crash with a CUDA out of memory error, and that also happens in their C++ counterparts. One such program is `cifar_vgg16_gn`. I just tried running the C++ version on a TITAN RTX with 24 GB of memory and it crashes with:

```
terminate called after throwing an instance of 'std::runtime_error'32 secs/batch
  what():  [CUDA ERROR]: out of memory (2) raised in create_tensor | (check_cuda)
```

The same happens to the Python version, of course. And that's the best CPU I have access to: the others have less than half that amount of memory. BTW, from what I see you're not using "full_mem" for all examples:

```console
[simleo@neuron:eddl ((V1.0.3b))]$ git grep CS_GPU -- examples/nn | grep low_mem | grep -v '// *cs'
examples/nn/1_mnist/10_mnist_rnn_func.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/11_mnist_conv1D.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/13_mnist_conv_dice.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/14_mnist_losses.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/1_mnist_mlp.cpp:        cs = CS_GPU({1},"low_mem"); // one GPU
examples/nn/1_mnist/2_mnist_mlp_initializers.cpp:        cs = CS_GPU({1},"low_mem"); // one GPU
examples/nn/1_mnist/3_mnist_mlp_regularizers.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/4_mnist_mlp_da.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/5_mnist_mlp_train_batch.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/6_mnist_auto_encoder.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/7_mnist_conv.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/8_mnist_rnn.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/1_mnist/9_mnist_mlp_func.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/2_cifar10/2_cifar_conv_da.cpp:        cs = CS_GPU({1}, "low_mem"); // one GPU
examples/nn/3_drive/1_drive_seg.cpp:        cs = CS_GPU({1,1}, 100, "low_mem"); // two GPU with weight sync every 10 batches
```
