### ISSUE TITLE
Difference in C++/Python API for pyeddl.eddl.save_net_to_onnx_file

### ISSUE THREAD

**Issue by thistlillo** [deephealthproject/pyeddl#76]
The PyEDDL function:

[pyeddl.eddl.save_net_to_onnx_file](https://deephealthproject.github.io/pyeddl/api/eddl.html#onnx-support) 

has two parameters, the network and the path, while the original C++ counterpart has three:

[void save_net_to_onnx_file(Net *net, string path, int seq_len = 0)](https://deephealthproject.github.io/eddl/model/onnx.html)

with the last one specifying the length of the input sequences.

It would be important to add the third parameter to the EDDL version because sometimes the export of networks with recurrent layers fails (with the latest 1.3 release) due to the seq_len value not being automatically set.

**Comment by thistlillo** [comment]
Grazie Simone, piu` o meno tra quanto tempo la modifica sara` disponibile su conda?

**Comment by simleo** [comment]
> Grazie Simone, piu' o meno tra quanto tempo la modifica sara' disponibile su conda?

If all goes well, by Monday (though some packages may start to pop up earlier).
